#!/usr/bin/env python
# -*- coding: utf-8 -*- 
import tkinter as tk

years = [5000, 5000, 5000, 5000, 5500, 5500, 10000, 5500, 5500, 5500, 6000, 6000]
date =  [2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020]
born_year = [1991, 1992, 1993, 1994, 1995, 1996, 1997 ,1998, 1999, 2000, 2001, 2002]
max_cotisation = sum(years)

val = date.index(2017)


window = tk.Tk()
window.title("Celi calculator")

# ----------------------------------- Functions ---------------------------------------


def celi_total_amount():

    age = int(ent_born.get())

    if age >= 1991 and age <= 2002 :
        birth_index = born_year.index(age)
        lbl_result_age["text"] = 'You can contribure an amount of ' +  str(max_cotisation - sum(years[0:birth_index]))+ '$'

    else :
        lbl_result_age["text"] = 'You need to be 18 years old to contribute to your Celi'


def celi_per_year ():

    celi_year = int(ent_year.get())

    if celi_year > 2009 and celi_year < 2021:
        index = date.index(celi_year)
        lbl_result_year["text"]= str(years[index]) + '$'

    else :
        lbl_result_year["text"]= "There is not enough data for this year."

def interest ():
    amount = float(ent_invest_amount.get())
    nb_years = float(ent_nb_years.get())
    interest = float(ent_interest_rate.get())
    result = amount * (1+(interest/100)* nb_years)

    lbl_interest_calculation_result["text"]= "Your investment of " + str(amount) + "$ will value " + str(result) + "$ after " + str(int(nb_years)) + " years"

# --------------------------------- GUI Widgets ----------------------------------


lbl_greeting = tk.Label(text = "Hello welcome to Celi calculator!", fg = "black")
lbl_greeting.pack()

# Calculation of the max amount you can have in your Celi base on your age
lbl_year_born = tk.Label(text = "When were you born?",fg = "black")
lbl_year_born.pack()

btn_year_born_submit = tk.Button(text="submit", fg = "blue", command = celi_total_amount)
btn_year_born_submit.pack()

ent_born = tk.Entry(fg="blue",width = 10)
ent_born.pack()

lbl_result_age = tk.Label(text= "")
lbl_result_age.pack()

# Calculation of the amount per year you can contribute to a Celi
lbl_celi_peryear = tk.Label(text = "Celi contribution amount per year",fg = "black")
lbl_celi_peryear.pack()

ent_year = tk.Entry(fg="blue", width = 10)
ent_year.pack()

btn_peryear_submit = tk.Button(text="submit", background = "green", fg = "blue",command = celi_per_year)
btn_peryear_submit.pack()

lbl_result_year = tk.Label(text = "")
lbl_result_year.pack()

# Calculation of the amount after interest on term
lbl_interest_calculation = tk.Label(text = "Interest calculation")
lbl_interest_calculation.pack()

lbl_invest_amount = tk.Label(text = "Invest amount ($)")
lbl_invest_amount.pack()

ent_invest_amount = tk.Entry(fg = "blue", width = 10)
ent_invest_amount.pack()

lbl_nb_years = tk.Label(text = "number of years")
lbl_nb_years.pack()

ent_nb_years = tk.Entry(fg = "blue", width = 10)
ent_nb_years.pack()

lbl_interest_rate = tk.Label(text = "Interest rate (%)")
lbl_interest_rate.pack()

ent_interest_rate = tk.Entry(fg = "blue", width = 10)
ent_interest_rate.pack()

btn_investment_submit = tk.Button(text="submit", background = "green", fg = "blue",command = interest)
btn_investment_submit.pack()

lbl_interest_calculation_result = tk.Label(text = "")
lbl_interest_calculation_result.pack()

window.mainloop()
